Supporting env file stored as CRLF

diff --git a/bin/direnv-x-print b/bin/direnv-x-print
--- a/bin/direnv-x-print
+++ b/bin/direnv-x-print
@@ -1,9 +1,9 @@
 #!/bin/bash
 
 
-set -Eeuo pipefail
 # shellcheck source=../..//bash-lib/lib/bashlib-error.sh
 source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-error.sh"
+error::set_strict_mode
 error::set_trap
 # shellcheck source=../..//bash-lib/lib/bashlib-echo.sh
 source "${BASHLIB_LIBRARY_PATH:-}${BASHLIB_LIBRARY_PATH:+/}bashlib-echo.sh"
@@ -52,20 +52,31 @@ for ENV_FILE in $ENV_FILES; do
       fi
       # Separate KEY and VALUE
       if [[ $LINE =~ ^([^=]+)=(.*)$ ]]; then
-          KEY=$(string::trim "${BASH_REMATCH[1]}")
-          KEY=${KEY^^} # Convert KEY to uppercase
-          VALUE=$(string::trim "${BASH_REMATCH[2]}")
+
+          # Note: You can't call any statement before ${BASH_REMATCH[1]} otherwise
+          # you get
+          # BASH_REMATCH[1]: unbound variable
+          KEY="${BASH_REMATCH[1]}"
+          VALUE="${BASH_REMATCH[2]}"
+          KEY=$(string::trim "${KEY^^}") # Convert KEY to uppercase and trim
+          VALUE=$(string::trim "${VALUE}")
+
+          echo::debug "Processing Key ($KEY) and value ($VALUE)"
 
           # If the value is a vault expression, get the value from the vault
           # or return the value otherwise
-          VALUE=$(vault::filter "$VALUE")
+          if ! VALUE=$(vault::filter "$VALUE"); then
+            echo::err "The vault value was not found for key ($KEY)"
+            exit 1
+          fi
 
           # Add the key to the OUTPUT_KEY_VALUES
           OUTPUT_KEY_VALUES["$KEY"]=$VALUE
 
       fi
   done <<< "$(
-                  cat "$ENV_FILE";
+                  # tr -d '\r' to remove the CR if the file is a windows file (ie CRLF)
+                  cat "$ENV_FILE" | tr -d '\r';
                   # If there is no new line at the end,
                   # the line is not processed by read
                   # https://stackoverflow.com/questions/20010741/why-does-unix-while-read-not-read-last-line
